import type React from 'react'

const s: Record<string, React.CSSProperties> = {
  app: {
    minHeight: '100vh',
    background: 'var(--surface-app)',
    color: 'var(--text-primary)',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  },
  header: {
    height: 56,
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    background: 'var(--surface-header)',
    borderBottom: '1px solid var(--border-subtle)',
    display: 'flex',
    alignItems: 'center',
    padding: '0 20px',
    position: 'sticky',
    top: 0,
    zIndex: 40,
    gap: 16,
  },
  logo: { fontWeight: 700, fontSize: 16, letterSpacing: '-0.02em', flexShrink: 0 },
  searchWrap: { flex: 1, display: 'flex', justifyContent: 'center' },
  searchInput: {
    width: 340,
    padding: '7px 14px',
    borderRadius: 10,
    border: '1px solid var(--border-subtle)',
    background: 'var(--surface-input)',
    color: 'var(--text-primary)',
    fontSize: 13,
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  count: { fontSize: 12, color: 'var(--text-muted)', fontWeight: 500, whiteSpace: 'nowrap' as const },
  addBtn: {
    padding: '6px 14px',
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 8,
    border: '1px solid var(--brand-border)',
    background: 'var(--brand-bg)',
    color: 'var(--brand-text)',
    cursor: 'pointer',
    transition: 'background 0.15s',
    whiteSpace: 'nowrap' as const,
  },
  body: { display: 'flex', height: 'calc(100vh - 56px)' },
  sidebar: {
    width: 220,
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    background: 'var(--surface-sidebar)',
    borderRight: '1px solid var(--border-subtle)',
    padding: '16px 10px',
    flexShrink: 0,
    overflowY: 'auto' as const,
  },
  sidebarSection: {
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.08em',
    color: 'var(--text-subtle)',
    padding: '4px 10px 8px',
  },
  catRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '7px 10px',
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 500,
    marginBottom: 2,
    transition: 'all 0.15s ease',
    cursor: 'default',
  },
  chevron: {
    width: 18,
    fontSize: 10,
    cursor: 'pointer',
    opacity: 0.5,
    flexShrink: 0,
    textAlign: 'center' as const,
  },
  badge: {
    fontSize: 10,
    background: 'var(--surface-pill)',
    borderRadius: 6,
    padding: '1px 6px',
    color: 'var(--text-subtle)',
    flexShrink: 0,
  },
  tagCloud: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 4,
    padding: '0 6px',
  },
  tagPill: {
    fontSize: 11,
    padding: '3px 8px',
    borderRadius: 6,
    border: '1px solid var(--border-subtle)',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  main: { flex: 1, padding: 24, overflowY: 'auto' as const },
  empty: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    height: '60vh',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
    gap: 20,
  },
  card: {
    position: 'relative' as const,
    background: 'var(--surface-card)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    border: '1px solid var(--border-subtle)',
    borderRadius: 14,
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  cardPreview: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 190,
    background: 'var(--surface-preview)',
    borderBottom: '1px solid var(--border-subtle)',
    position: 'relative' as const,
    overflow: 'hidden' as const,
  },
  previewOverlay: {
    position: 'absolute' as const,
    inset: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    background: 'rgba(8,10,14,0.62)',
    backdropFilter: 'blur(4px)',
    WebkitBackdropFilter: 'blur(4px)',
    padding: 12,
    textAlign: 'center' as const,
  },
  previewSpinner: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: '2px solid rgba(255,255,255,0.2)',
    borderTopColor: 'rgba(255,255,255,0.9)',
    animation: 'spin 0.9s linear infinite',
  },
  previewOverlayText: {
    fontSize: 12,
    fontWeight: 500,
    color: 'var(--text-secondary)',
  },
  previewErrorTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: '#ffb4b4',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
  },
  previewErrorText: {
    fontSize: 11,
    color: '#ffd2d2',
    maxWidth: 220,
    lineHeight: 1.4,
    wordBreak: 'break-word' as const,
  },
  cardOverlay: {
    position: 'absolute' as const,
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    background: 'rgba(0,0,0,0.5)',
    backdropFilter: 'blur(4px)',
    WebkitBackdropFilter: 'blur(4px)',
    zIndex: 2,
  },
  cardBtn: {
    padding: '4px 10px',
    fontSize: 11,
    fontWeight: 500,
    borderRadius: 6,
    border: '1px solid var(--border-strong)',
    background: 'var(--surface-button)',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  cardInfo: { padding: '14px 14px 13px' },
  cardTitle: { fontSize: 14, fontWeight: 600, letterSpacing: '-0.01em' },
  itemMeta: { fontSize: 11, color: 'var(--text-subtle)', marginTop: 4, textTransform: 'capitalize' as const },
  cardSub: { fontSize: 11, color: 'var(--text-subtle)', marginTop: 3, textTransform: 'capitalize' as const },
  cardTag: {
    fontSize: 10,
    padding: '1px 6px',
    borderRadius: 4,
    background: 'var(--surface-pill)',
    color: 'var(--text-muted)',
  },
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    zIndex: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--surface-overlay)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
  },
  modal: {
    background: 'var(--surface-modal)',
    border: '1px solid var(--border-subtle)',
    borderRadius: 16,
    width: '92vw',
    maxWidth: 1000,
    maxHeight: '88vh',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
    boxShadow: '0 30px 80px rgba(0,0,0,0.6)',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 20px',
    borderBottom: '1px solid var(--border-subtle)',
  },
  modalTab: {
    padding: '5px 12px',
    fontSize: 12,
    borderRadius: 7,
    border: '1px solid var(--border-strong)',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  modalClose: {
    padding: '5px 10px',
    fontSize: 12,
    borderRadius: 7,
    border: '1px solid var(--border-subtle)',
    background: 'var(--surface-button)',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    marginLeft: 4,
  },
  modalContent: {
    flex: 1,
    display: 'flex',
    overflow: 'hidden',
  },
  modalMain: {
    flex: 1,
    overflow: 'auto',
    padding: 20,
  },
  modalMeta: {
    width: 224,
    borderLeft: '1px solid var(--border-subtle)',
    padding: '20px 16px',
    overflowY: 'auto' as const,
    flexShrink: 0,
  },
  metaSection: { marginBottom: 18 },
  metaLabel: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.08em',
    color: 'var(--text-subtle)',
    marginBottom: 4,
  },
  metaValue: {
    fontSize: 12,
    color: 'var(--text-secondary)',
    textTransform: 'capitalize' as const,
    lineHeight: 1.4,
  },
  metaTag: {
    fontSize: 10,
    padding: '3px 7px',
    borderRadius: 4,
    background: 'rgba(140,130,255,0.12)',
    color: 'rgba(200,195,255,0.7)',
  },
  deleteBtn: {
    marginTop: 12,
    padding: '8px 0',
    width: '100%',
    fontSize: 12,
    fontWeight: 500,
    borderRadius: 8,
    border: '1px solid rgba(255,80,80,0.2)',
    background: 'rgba(255,80,80,0.08)',
    color: 'rgba(255,120,120,0.8)',
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  previewArea: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 320,
    background: 'var(--surface-preview)',
    borderRadius: 12,
    border: '1px solid var(--border-subtle)',
  },
  copyBtn: {
    position: 'absolute' as const,
    top: 10,
    right: 10,
    padding: '5px 12px',
    fontSize: 11,
    borderRadius: 6,
    border: '1px solid var(--border-strong)',
    background: 'var(--surface-button)',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  codeBlock: {
    background: 'var(--surface-code)',
    border: '1px solid var(--border-subtle)',
    borderRadius: 12,
    padding: 16,
    fontSize: 12,
    color: 'var(--text-secondary)',
    overflow: 'auto',
    maxHeight: '65vh',
    lineHeight: 1.6,
  },
  formLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--text-muted)',
    marginBottom: 6,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  formInput: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid var(--border-strong)',
    background: 'var(--surface-input)',
    color: 'var(--text-primary)',
    fontSize: 13,
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  submitBtn: {
    padding: '10px 20px',
    fontSize: 13,
    fontWeight: 600,
    borderRadius: 10,
    border: '1px solid var(--brand-border)',
    background: 'var(--brand-bg)',
    color: 'var(--brand-text)',
    cursor: 'pointer',
    transition: 'background 0.15s',
    marginTop: 4,
  },
}

export { s }

